// <auto-generated />
namespace pharmsquare_prototype.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class select : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(select));
        
        string IMigrationMetadata.Id
        {
            get { return "202112062008503_select"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
