// <auto-generated />
namespace pharmsquare_prototype.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class select2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(select2));
        
        string IMigrationMetadata.Id
        {
            get { return "202112062017447_select2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
